# Generated by Django 5.0.2 on 2024-02-13 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0004_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Part-time', 'Part-time'), ('Full-time', 'Full-time')], default='Part-time', max_length=30)),
                ('date_of_joining', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('type', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract')], default='Contract', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Office.branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Office.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Office.user')),
            ],
        ),
    ]
