# Generated by Django 5.0.2 on 2024-02-13 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0007_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('emergency_contact', models.IntegerField()),
                ('employee_photo', models.ImageField(upload_to='employee_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Office.employee')),
            ],
        ),
    ]
