# Generated by Django 5.0.2 on 2024-02-13 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0009_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Punch In', 'Punch In'), ('Punch Out', 'Punch Out'), ('Break In', 'Break In'), ('Break Out', 'Break Out')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Office.attendance')),
            ],
        ),
    ]
