# Generated by Django 5.0.2 on 2024-02-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0011_leavetype_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
